### ISSUE TITLE
Add Support for Expo SDK 52

### ISSUE THREAD

**Issue by diegocuehdz** [aptabase/aptabase-react-native#11]
Description
Expo SDK 52 has been released as of November 12th 2024, hope to have this new version in order to be able to update to the new react native architecture in my projects.

[ExpoSDK-52 Changelog](https://expo.dev/changelog/2024/11-12-sdk-52)

Would be nice to now the time estimate to have this update in case that I need to remove bugsnag dependency for the time being in order to update the SDK to the latest.

As always thank you very much for your support.

**Comment by Robert27** [comment]
Aptabase already supports the new arch, see the [RN directory](https://reactnative.directory/?search=aptabase).
Also I have not noticed any issues in my own apps using Expo SDK 52 with the new arch.

**Comment by diegocuehdz** [comment]
@Robert27 your absolutely right, I think it was an issue with expo 52 first versions. I've retested on expo 52.0.19 and everything works without any problem. 
I'm closing this issue.

As always, thank you very much for the support and great work, and amazing product!
