### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by tomhopkins** [aptabase/aptabase-react-native#6]
Hi,

Thanks for a great package. Can I ask about an apparent inconsistency with documentation. On the aptabase site, it suggests the SDK is integrated using the init command in index.js ('before App is declared'). In the github docs it shows it as wrapper in the App.js file. 

I have it working with the former method on iOS but it is throwing errors on Android? 

Thanks

Tom

**Comment by goenning** [comment]
Hey @tomhopkins 

That was a recent change, we previously suggested calling init + importing trackEvent, with the newer version there's a Context provider + hook that is more idiomatic for React/React Native apps.

I've updated the docs to recommend using the newer approach, but I might have missed some pages. Where did you see the use of `init` on our website? 

However, both methods should still work OK. What errors do you get on Android? Is it on a real device or emulator?

**Comment by tomhopkins** [comment]
It was here (https://eu.aptabase.com/NJvCjlqPhd2wDw24Xoboru/instructions) but it is now updated. What do I import in App? Sorry if that's obvious but I tried { AptabaseProvider } and it didn't exist.

**Comment by goenning** [comment]
I'll update the docs to include the import too, it should be:

```ts
import { AptabaseProvider } from "@aptabase/react-native"
```

Are you on version 0.3.0 of the package?

**Comment by tomhopkins** [comment]
No, it's installing 0.2.2

**Comment by tomhopkins** [comment]
Ok, I have 0.3.0 now, rebuilding my development versions and will let you know if I have problems. I notice you've also changed the tracking method in the notes. Will it still work to import { trackEvent } and then use it directly, or should I change all instance to import { useAptabase } and then do const { trackEvent }  = useAptabase ()?

Thanks again. Very nice tool.

**Comment by goenning** [comment]
I'd recommend using the hook as things might change in future, but the previous method of importing the function also works

**Comment by tomhopkins** [comment]
Thanks and the errors were on android emulator. I’ll post them in a sec if still present.

**Comment by tomhopkins** [comment]
Ok, still seeing the errors. This is in an Android simulator, same build apparently working 100% on ios:

Aptabase: Failed to send 4 events because of 400 {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-ec53d5b7da5727de8cb770466806a6a4-827f63dbce9cd376-00","errors":{"events":["The events field is required."],"$[0].systemProps.appBuildNumber":["The JSON value could not be converted to System.String. Path: $[0].systemProps.appBuildNumber | LineNumber: 0 | BytePositionInLine: 251."]}}. Will not retry.

**Comment by goenning** [comment]
Are you using bare react native or is it expo?

I think I found the root cause, can you try using version 0.3.1 of the SDK (just released).

**Comment by tomhopkins** [comment]
Yes, that appears to have worked. Thanks.

**Comment by goenning** [comment]
Great! Thanks for confirming it!
