### ISSUE TITLE
Aptabase does not support Jest out of the box

### ISSUE THREAD

**Issue by javialgaba** [aptabase/aptabase-react-native#8]
This library doesn't work with Jest. Whenever a test that imports the library is run, the following exception is raised: `SyntaxError: Cannot use import statement outside a module.`

While this issue is being resolved, I've created the following mock to prevent my tests from breaking. But it would be ideal if the library itself provided this functionality.

```
jest.mock('@aptabase/react-native', () => ({
  AptabaseProvider: ({ children }) => {
    return <>{children}</>
  },
  trackEvent: jest.fn(),
}));
```

Thank you!

**Comment by goenning** [comment]
Thanks for the report @javialgaba 

im not sure what’s causing this but I’ll try reproduce it.

If you could share the complete stack trace that would help a lot!

**Comment by goenning** [comment]
Hi @javialgaba I took some time to look at this.

It seems like expo recommends to configure jest to ignore transformation of all its modules: https://docs.expo.dev/develop/unit-testing/#configuration

I added `|@aptabase/.*` at the end of `transformIgnorePatterns` and it worked for me. 
Can you give it a try in your project?

```
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@aptabase/.*)"
    ]
```

**Comment by goenning** [comment]
And I'd also recommend skipping `init` during unit tests:

```js
if (process.env.NODE_ENV !== 'test') {
  Aptabase.init("A-EU-...."); 
}
```

**Comment by javialgaba** [comment]
@goenning This works as well, thanks.
